### PR TITLE
Update oauth authorize_url

### PR DESCRIPTION
**Pull request by jamescook**
https://github.com/tkgospodinov/omniauth-fitbit/issues/14

@ElMassimo @jeremiahlee

### CODE REVIEW

**Comment by charlieok** [comment]
:+1:

**Comment by 11mdlow** [comment]
we can we expect a new version of this gem to be available? We got that email too about using the wrong API url and would like to fix it soon

**Comment by tkgospodinov** [comment]
I just released 1.0.5 which has the fix --
https://rubygems.org/gems/omniauth-fitbit/versions/1.0.5

**Comment by 11mdlow** [comment]
awesome, thanks for the quick release!

**Comment by tkgospodinov** [comment]
No worries, let me know if you run into any problems with it.

**Pull request merged**
