### PR TITLE
Add :display to authorize_params

### PR DESCRIPTION
**Pull request by iamjarvo**

### CODE REVIEW

**Comment by iamjarvo** [comment]
This adds the display option. The display option allows the user to specify how to show the auth page. The options I know of are display=touch(mobile) and display=page(webpage)

**Comment by iamjarvo** [comment]
Anything I can do to help get this merged?

**Comment by tkgospodinov** [comment]
Sorry for the delay, I'll get it merged and released.

**Comment by iamjarvo** [comment]
Thanks!

**Comment by tkgospodinov** [comment]
The %i modifier requires ruby > 2.0. Can you update it so we can preserve compatibility with < 2.0, and I will release the new version. Thanks for your contribution!

**Pull request merged**
